const WishlistActionTypes = {
    TOGGLE_WISHLIST: 'TOGGLE_WISHLIST',
    ADD_WISHLIST: 'ADD_WISHLIST',
    CLEAR_ITEM_FROM_WISHLIST: 'CLEAR_ITEM_FROM_WISHLIST',
    CLEAR_WISHLIST: 'CLEAR_WISHLIST'
};

export default WishlistActionTypes;